In [1]:
import os
os.chdir("..")

In [2]:
import pandas as pd
from src.utils import load_json

In [3]:
ROOT = "./reports/metrics"

In [4]:
def load_metric_json(pth: str) -> dict:
    data = load_json(pth)
    nested = {
        (k, vi): vv
        for k, v in data.items()
        if isinstance(v, dict)
        for vi, vv in v.items()
    }

    flat = {
        (k, ""): v for k, v in data.items() if not isinstance(v, dict)
    }
    return {**nested, **flat}

In [5]:
results = dict()
for (root, _, files) in filter(lambda x: x[1] == [], os.walk(ROOT)):
    for file in files:
        metrics = load_metric_json(f"{root}/{file}")
        row_index = *(root.split(ROOT)[1].split("/")[1:]), file.split(".json")[0]
        results.update({row_index: metrics})
results_df = pd.DataFrame(results).T

In [6]:
results_df

                                 component_rouge_score                   \
                                       rouge1_fmeasure rouge1_precision
dataset2 edge_types labels                    0.519975         0.492934
                    descriptions              0.118604         0.100303
         node_types labels                         NaN              NaN
                    descriptions                   NaN              NaN
dataset1 edge_types labels                    0.626713         0.578080
                    descriptions              0.127481         0.112906
         node_types labels                         NaN              NaN
                    descriptions                   NaN              NaN

                                                                \
                                 rouge1_recall rouge2_fmeasure
dataset2 edge_types labels            0.634349        0.295508
                    descriptions      0.194019        0.017361
         node_types labels                 NaN             NaN
                    descriptions           NaN             NaN
dataset1 edge_types labels            0.758207        0.446112
                    descriptions      0.186973        0.020051
         node_types labels                 NaN             NaN
                    descriptions           NaN             NaN

                                                                 \
                                 rouge2_precision rouge2_recall
dataset2 edge_types labels               0.285019      0.343454
                    descriptions         0.014082      0.030767
         node_types labels                    NaN           NaN
                    descriptions              NaN           NaN
dataset1 edge_types labels               0.417431      0.541066
                    descriptions         0.018109      0.029057
         node_types labels                    NaN           NaN
                    descriptions              NaN           NaN

                                                                   \
                                 rougeL_fmeasure rougeL_precision
dataset2 edge_types labels              0.519599         0.492334
                    descriptions        0.099679         0.083902
         node_types labels                   NaN              NaN
                    descriptions             NaN              NaN
dataset1 edge_types labels              0.625824         0.577116
                    descriptions        0.106331         0.094071
         node_types labels                   NaN              NaN
                    descriptions             NaN              NaN

                                                                   ...  \
                                 rougeL_recall rougeLsum_fmeasure  ...
dataset2 edge_types labels            0.634039           0.519599  ...
                    descriptions      0.166114           0.101866  ...
         node_types labels                 NaN                NaN  ...
                    descriptions           NaN                NaN  ...
dataset1 edge_types labels            0.757325           0.625824  ...
                    descriptions      0.158260           0.109103  ...
         node_types labels                 NaN                NaN  ...
                    descriptions           NaN                NaN  ...

                                 root_rouge_score                   \
                                  rougeL_fmeasure rougeL_precision
dataset2 edge_types labels                    NaN              NaN
                    descriptions              NaN              NaN
         node_types labels               0.023915         0.023191
                    descriptions         0.109996         0.078792
dataset1 edge_types labels                    NaN              NaN
                    descriptions              NaN              NaN
         node_types labels               0.091980         0.108390
                    descriptions         0.132685         0.109806

                                                                   \
                                 rougeL_recall rougeLsum_fmeasure
dataset2 edge_types labels                 NaN                NaN
                    descriptions           NaN                NaN
         node_types labels            0.033654           0.023915
                    descriptions      0.209259           0.109996
dataset1 edge_types labels                 NaN                NaN
                    descriptions           NaN                NaN
         node_types labels            0.084548           0.091980
                    descriptions      0.216674           0.132762

                                                                       \
                                 rougeLsum_precision rougeLsum_recall
dataset2 edge_types labels                       NaN              NaN
                    descriptions                 NaN              NaN
         node_types labels                  0.023191         0.033654
                    descriptions            0.078792         0.209259
dataset1 edge_types labels                       NaN              NaN
                    descriptions                 NaN              NaN
         node_types labels                  0.108390         0.084548
                    descriptions            0.109905         0.216737

                                 combined_sam_score negative_sem_score  \

dataset2 edge_types labels                      NaN                NaN
                    descriptions                NaN                NaN
         node_types labels                 0.291806           0.154326
                    descriptions           0.326702           0.140064
dataset1 edge_types labels                      NaN                NaN
                    descriptions                NaN                NaN
         node_types labels                 0.259323           0.233195
                    descriptions           0.258188           0.221584

                                 positive_sem_score root_sem_score

dataset2 edge_types labels                      NaN            NaN
                    descriptions                NaN            NaN
         node_types labels                 0.523559       0.368704
                    descriptions           0.468795       0.464738
dataset1 edge_types labels                      NaN            NaN
                    descriptions                NaN            NaN
         node_types labels                 0.652262       0.332774
                    descriptions           0.519100       0.440444

[8 rows x 65 columns]

In [7]:
node_type_res = results_df.loc[(slice(None), "node_types", slice(None)), results_df.columns.get_level_values(1).str.contains("fmeasure", na=False) |
    (results_df.columns.get_level_values(1) == "")].dropna(axis=1, how="all")
node_type_res

                                 combined_rouge_score                  \
                                      rouge1_fmeasure rouge2_fmeasure
dataset2 node_types labels                   0.081251        0.026902
                    descriptions             0.077319        0.016981
dataset1 node_types labels                   0.241366        0.139621
                    descriptions             0.131776        0.047300

                                                                     \
                                 rougeL_fmeasure rougeLsum_fmeasure
dataset2 node_types labels              0.081251           0.081251
                    descriptions        0.066153           0.066153
dataset1 node_types labels              0.241203           0.241203
                    descriptions        0.117244           0.117501

                                 negative_rouge_score                  \
                                      rouge1_fmeasure rouge2_fmeasure
dataset2 node_types labels                   0.023915        0.005644
                    descriptions             0.026695        0.003553
dataset1 node_types labels                   0.037572        0.005543
                    descriptions             0.032228        0.002523

                                                                     \
                                 rougeL_fmeasure rougeLsum_fmeasure
dataset2 node_types labels              0.023915           0.023915
                    descriptions        0.023538           0.023538
dataset1 node_types labels              0.037572           0.037572
                    descriptions        0.028540           0.028540

                                 positive_rouge_score                  \
                                      rouge1_fmeasure rouge2_fmeasure
dataset2 node_types labels                   0.177296        0.065093
                    descriptions             0.073975        0.018299
dataset1 node_types labels                   0.456778        0.262660
                    descriptions             0.165862        0.072371

                                                                     \
                                 rougeL_fmeasure rougeLsum_fmeasure
dataset2 node_types labels              0.177296           0.177296
                    descriptions        0.069444           0.069444
dataset1 node_types labels              0.456778           0.456778
                    descriptions        0.157406           0.157843

                                 root_rouge_score                  \
                                  rouge1_fmeasure rouge2_fmeasure
dataset2 node_types labels               0.023915        0.005644
                    descriptions         0.134111        0.022762
dataset1 node_types labels               0.092306        0.021315
                    descriptions         0.161866        0.025939

                                                                     \
                                 rougeL_fmeasure rougeLsum_fmeasure
dataset2 node_types labels              0.023915           0.023915
                    descriptions        0.109996           0.109996
dataset1 node_types labels              0.091980           0.091980
                    descriptions        0.132685           0.132762

                                 combined_sam_score negative_sem_score  \

dataset2 node_types labels                 0.291806           0.154326
                    descriptions           0.326702           0.140064
dataset1 node_types labels                 0.259323           0.233195
                    descriptions           0.258188           0.221584

                                 positive_sem_score root_sem_score

dataset2 node_types labels                 0.523559       0.368704
                    descriptions           0.468795       0.464738
dataset1 node_types labels                 0.652262       0.332774
                    descriptions           0.519100       0.440444

In [8]:
edge_type_res = results_df.loc[(slice(None), "edge_types", slice(None)), results_df.columns.get_level_values(1).str.contains("fmeasure", na=False) |
    (results_df.columns.get_level_values(1) == "")].dropna(axis=1, how="all")
edge_type_res

                                 component_rouge_score                  \
                                       rouge1_fmeasure rouge2_fmeasure
dataset2 edge_types labels                    0.519975        0.295508
                    descriptions              0.118604        0.017361
dataset1 edge_types labels                    0.626713        0.446112
                    descriptions              0.127481        0.020051

                                                                     \
                                 rougeL_fmeasure rougeLsum_fmeasure
dataset2 edge_types labels              0.519599           0.519599
                    descriptions        0.099679           0.101866
dataset1 edge_types labels              0.625824           0.625824
                    descriptions        0.106331           0.109103

                                 component_sem_score

dataset2 edge_types labels                  0.550977
                    descriptions            0.309089
dataset1 edge_types labels                  0.523062
                    descriptions            0.258767

In [9]:
print(node_type_res.sort_index().to_latex(float_format="%.2f"))

\begin{tabular}{lllrrrrrrrrrrrrrrrrrrrr}
\toprule
 &  &  & \multicolumn{4}{r}{combined_rouge_score} & \multicolumn{4}{r}{negative_rouge_score} & \multicolumn{4}{r}{positive_rouge_score} & \multicolumn{4}{r}{root_rouge_score} & combined_sam_score & negative_sem_score & positive_sem_score & root_sem_score \\
 &  &  & rouge1_fmeasure & rouge2_fmeasure & rougeL_fmeasure & rougeLsum_fmeasure & rouge1_fmeasure & rouge2_fmeasure & rougeL_fmeasure & rougeLsum_fmeasure & rouge1_fmeasure & rouge2_fmeasure & rougeL_fmeasure & rougeLsum_fmeasure & rouge1_fmeasure & rouge2_fmeasure & rougeL_fmeasure & rougeLsum_fmeasure &  &  &  &  \\
\midrule
\multirow[t]{2}{*}{dataset1} & \multirow[t]{2}{*}{node_types} & descriptions & 0.13 & 0.05 & 0.12 & 0.12 & 0.03 & 0.00 & 0.03 & 0.03 & 0.17 & 0.07 & 0.16 & 0.16 & 0.16 & 0.03 & 0.13 & 0.13 & 0.26 & 0.22 & 0.52 & 0.44 \\
 &  & labels & 0.24 & 0.14 & 0.24 & 0.24 & 0.04 & 0.01 & 0.04 & 0.04 & 0.46 & 0.26 & 0.46 & 0.46 & 0.09 & 0.02 & 0.09 & 0.09 & 0.26 & 0.23 & 0.65 & 0.33 \\
\cline{1-23} \cline{2-23}
\multirow[t]{2}{*}{dataset2} & \multirow[t]{2}{*}{node_types} & descriptions & 0.08 & 0.02 & 0.07 & 0.07 & 0.03 & 0.00 & 0.02 & 0.02 & 0.07 & 0.02 & 0.07 & 0.07 & 0.13 & 0.02 & 0.11 & 0.11 & 0.33 & 0.14 & 0.47 & 0.46 \\
 &  & labels & 0.08 & 0.03 & 0.08 & 0.08 & 0.02 & 0.01 & 0.02 & 0.02 & 0.18 & 0.07 & 0.18 & 0.18 & 0.02 & 0.01 & 0.02 & 0.02 & 0.29 & 0.15 & 0.52 & 0.37 \\
\cline{1-23} \cline{2-23}
\bottomrule
\end{tabular}

In [10]:
print(edge_type_res.sort_index().to_latex(float_format="%.2f"))

\begin{tabular}{lllrrrrr}
\toprule
 &  &  & \multicolumn{4}{r}{component_rouge_score} & component_sem_score \\
 &  &  & rouge1_fmeasure & rouge2_fmeasure & rougeL_fmeasure & rougeLsum_fmeasure &  \\
\midrule
\multirow[t]{2}{*}{dataset1} & \multirow[t]{2}{*}{edge_types} & descriptions & 0.13 & 0.02 & 0.11 & 0.11 & 0.26 \\
 &  & labels & 0.63 & 0.45 & 0.63 & 0.63 & 0.52 \\
\cline{1-8} \cline{2-8}
\multirow[t]{2}{*}{dataset2} & \multirow[t]{2}{*}{edge_types} & descriptions & 0.12 & 0.02 & 0.10 & 0.10 & 0.31 \\
 &  & labels & 0.52 & 0.30 & 0.52 & 0.52 & 0.55 \\
\cline{1-8} \cline{2-8}
\bottomrule
\end{tabular}